common:
  seed: 2025
  verbose: true
  exp_dir: experiments

dataset:
  batch_size: 128
  dataset: mit_bih_dataset.MITBIHDataset
  num_workers: 8
  root_path:
    train: './data/original/physionet.org/files/mitdb/1.0.0'
    val:
    test: 
  io_path:
    train: "./data/tyee/tyee_mit_bih/train"
    val: 
    test: 
  io_mode: hdf5
  io_chunks: 128
  split: 
    select: HoldOut
    init_params:
      split_path: ./data/tyee//tyee_mit_bih/split
      val_size: 0.1
      random_state: 7
      shuffle: true
      stratify: symbol
  before_segment_transform:
    - select: PickChannels
      channels: ['MLII']
      source: ecg
      target: ecg
    - select: ZScoreNormalize
      axis: 1
      source: ecg
      target: ecg
  offline_label_transform:
    - select: Mapping
      mapping:
        'N': 0
        'V': 1
        '/': 2
        'R': 3
        'L': 4
        'A': 5
        '!': 6
        'E': 7
      source: symbol
      target: symbol


model:
  select: ecgresnet34.EcgResNet34


optimizer:
  lr:  0.001
  select: Adam

task:
  loss:
    select: CrossEntropyLoss
  select: mit_bih_task.MITBIHTask

trainer:
  fp16: false
  total_epochs: 650
  update_interval: 1
  log_interval: 20
  eval_metric:
    select: accuracy
    mode: max
  metrics: [accuracy, precision_macro, f1_macro, recall_macro]
    

distributed:
  backend: nccl
  world_size: 1
  distributed_no_spawn: false