common:
  seed: 42
  verbose: true
  exp_dir: experiments

dataset:
  batch_size: 128
  dataset: mm_aad_dataset.MMAADDataset
  num_workers: 8
  root_path:
    train: '/home/data/lingyus/EEG-AAD/EEG-AAD_audio_visual/preprocessed/'
    val:
    test:
  io_path:
    train: "/home/lingyus/data/tyee_eegaad"
    val:
    test:
  io_mode: hdf5
  split: 
    select: HoldOutCrossByIds
    init_params:
      split_path: /home/lingyus/data/mm_aad_split
      group_by: subject_id
      val_ids: [1,2,3,6]
  
  online_signal_transform:
    - select: Transpose
      source: eeg
      target: eeg
  online_label_transform:
    - select: Squeeze
      source: label
      target: label
      


model:
  select: darnet.DARNet
  channel_size: 32

    
optimizer:
  lr: 5e-4
  select: AdamW
  weight_decay: 3e-4             

task:
  loss:
    select: CrossEntropyLoss
  select: aad_task.AADTask

trainer:
  fp16: false
  total_epochs: 100
  update_interval: 1
  # eval_interval: 10
  log_interval: 20
  eval_metric:
    select: accuracy
    mode: max
  metrics: [accuracy]
    

distributed:
  backend: nccl
  world_size: 1
  distributed_no_spawn: false