common:
  seed: 42
  verbose: true
  exp_dir: experiments

dataset:
  batch_size: 32
  dataset: CarDataset
  eval:
  - car_dev.txt
  - car_test.txt
  num_workers: 2
  path: data
  train: car_1000.txt
  transforms:
    select: []

lr_scheduler:
  gamma: 0.1
  select: StepLR
  step_size: 20

model:
  downstream:
    classes: 4
    select: MLP
  upstream:
    select: MLP
    trainable: true

optimizer:
  lr: 0.01
  select: Adam

task:
  loss:
    select: CrossEntropyLoss
    weight:
    - 1.0
    - 1.0
    - 1.0
    - 2.0
  select: EmotionRecognitionTask

trainer:
  ddp_backend: gloo
  fp16: false
  total_steps: 1000
  save_interval: 20
  eval_interval: 20
  log_interval: 20
  world_size: 1
  eval_metric: Accuracy
  metrics:
    Accuracy: {}
    Precision:
      average: "micro"
    Recall:
      average: "micro"
    F1:
      average: "micro"
