common:
  seed: 42
  verbose: true
  root: experiments

dataset:
  batch_size: 32
  dataset: BaseDataset
  num_workers: 2
  root_path:
    train:
    val:
    test:
  io_path:
    train:
    val:
    test:
  io_mode: # 'lmdb', 'pickle', 'memory'
  split: 
    method: none
    # other prams

    # method: none

    # method: train_test_split
    # test_size: 0.2
    # random_state: 42

    # method: kfold
    # n_splits: 5
    # shuffle: true
  offline_transform:
    eeg:
      pick_channels:
        channels:
      oreder_channels:
        channels:
      filter:
        l_freq: 0.5
        h_freq: 75
      notch_filter:
        freqs: [50]
      resample:
        sfreq: 200
  online_transform:
  label_transform:

lr_scheduler:
  gamma: 0.1
  select: StepLR
  step_size: 20

model:
  select: MLP
  trainable: true

optimizer:
  lr: 0.01
  select: Adam

task:
  loss:
    select: CrossEntropyLoss
    weight:
    - 1.0
    - 1.0
    - 1.0
    - 2.0
  select: EmotionRecognitionTask

trainer:
  resume:  # 添加断点恢复配置
      enabled: true
      checkpoint: /home/lingyus/code/PRL/experiments/2025-01-10/14-27-21/checkpoint/checkpoint_step_8488.pt
  fp16: false
  total_steps: 1000
  total_epoches:
  update_interval: 1
  save_interval: 20
  eval_interval: 20
  log_interval: 20
  eval_metric:
    select: balanced_accuracy
    mode: max
  metrics: [balanced_accuracy, accuracy, f1_weighted, cohen_kappa]

distributed:
  backend: nccl
  world_size: 1
  distributed_no_spawn: false