

trainer:
  fp16: true
  world_size: 4
  ddp_backend: legacy_ddp


dataset:
  num_workers: 2
  path: /path/to/data
  train: train
  eval: 
    - dev
    - test
  transforms:
    select: []

model:
  upstream: 
    select: fbank.FBank

  downstream: 
    select: demo.Demo
    classes: 2


task:
  select: classification

  loss:
    select: CrossEntropyLoss  # 指定损失函数
    weight: [1.0, 1.5]  # 配置损失函数的超参数，如类别权重等

optimizer:
  select: Adam


lr_scheduler:
  select: CosineLR

