common:
  seed: 0
  verbose: true
  exp_dir: experiments

dataset:
  batch_size: 64
  dataset: bciciv4_dataset.BCICIV4Dataset
  num_workers: 8
  root_path:
    train: '/home/lingyus/data/BCICIV4/sub1'
    val:
    # test: 
  io_path:
    train: "/home/lingyus/data/BCICIV4/sub1/processed_test"
    val: 
    test: 
  io_mode: hdf5
  io_chunks: 256
  split: 
    select: HoldOutCross
    init_params:
      split_path: /home/lingyus/data/BCICIV4/sub1/split
      group_by: trial_id
      val_size: 0.5
      random_state: 0
      shuffle: true

 


# lr_scheduler:
#   select: WarmupCosineScheduler
#   total_epochs: 200
#   eta_min: 1e-6
#   warmup_start_lr: 0
#   warmup_epochs: 5

model:
  select: fingerflex.AutoEncoder1D
  channels: [32, 32, 64, 64, 128, 128]
  kernel_sizes: [7, 7, 5, 5, 5]
  strides: [2, 2, 2, 2, 2]
  dilation: [1, 1, 1, 1, 1]
  n_electrodes: 62
  n_freqs: 40
  n_channels_out: 5

    

optimizer:
  lr:  8.42e-5
  select: Adam
  weight_decay: 1e-6             # 权重衰减 (L2正则化)
  # layer_decay: 0.65                # 层级学习率衰减

task:
  loss:
    select: MSELoss
    # smoothing: 0.1
  select: bciciv4_task.BCICIV4Task

trainer:
  resume:  # 添加断点恢复配置
      enabled: false
      checkpoint: /home/lingyus/code/PRL/experiments/2025-01-10/14-27-21/checkpoint/checkpoint_step_8488.pt
  fp16: false
  # total_steps: 31980
  total_epochs: 20
  update_interval: 1
  # save_interval: 1066
  # eval_interval: 1066
  log_interval: 20
  eval_metric:
    select: mean_cc
    mode: max
  metrics: [mean_cc]
    

distributed:
  backend: nccl
  world_size: 1
  distributed_no_spawn: false