
dataset:
  batch_size: 32
  dataset: CarDataset
  eval:
  - car_dev.txt
  - car_test.txt
  num_workers: 2
  path: data\
  train: car_train.txt
  transforms:
    select:
    - MFCC

lr_scheduler:
  gamma: 0.1
  select: StepLR
  step_size: 20

model:
  downstream:
    classes: 4
    select: MLP
  upstream:
    select: EEG2MSVec
    trainable: false
    expert:
      enable: true
      hooks:
        module_path: 
          - self.model.encoder.final_fused_layer
        transform: "lambda input, output: output"
  
optimizer:
  lr: 0.01
  select: SGD

task:
  select: EmotionRecognitionTask

  loss:
    select: CrossEntropyLoss
    weight:
    - 1.0
    - 1.0
    - 1.0
    - 2.0
  

trainer:
  ddp_backend: gloo
  fp16: false
  save_epoch: 20
  total_epochs: 100
  valid_epoch: 20
  world_size: 1
