common:
  seed: 8
  verbose: true
  exp_dir: experiments

dataset:
  batch_size: 64
  dataset: BCICIV2ADataset
  num_workers: 0
  path: /mnt/ssd/lingyus/BCICIV2a/BCIC_2a_row
  test_subject: 9
  

lr_scheduler:
  select: OneCycleLR
  total_steps: 6500
  pct_start: 0.2
  max_lr: 4e-4
model:
  upstream:
    select: EEGPT_BCICIV2A
    checkpoint: /home/lingyus/code/PRL/models/upstream/eegpt/checkpoint/eegpt_mcae_58chs_4s_large4E.ckpt

optimizer:
  lr: 4e-4
  select: AdamW
  weight_decay: 0.01            # 权重衰减 (L2正则化)
  

task:
  loss:
    select: CrossEntropyLoss
  select: BCICIV2ATask

trainer:
  ddp_backend: gloo
  fp16: true
  total_steps: 6500
  save_interval: 65
  eval_interval: 65
  log_interval: 10
  world_size: 1
  eval_metric: BalancedAccuracy
  metrics:
    acc: {}
    bal_acc: {}
    f1:
      average: 'weighted'
    cohen_kappa: {}

distributed:
  backend: nccl
  world_size: 2
  rank: 0
  distributed_no_spawn: false
  cuda_visible_devices: "2,3"  