common:
  seed: 7
  verbose: true
  exp_dir: experiments

dataset:
  batch_size: 32
  dataset: PhysioP300Dataset
  num_workers: 8
  path: /mnt/ssd/lingyus/PhysioNetP300
  train_subjects: [1,2,3,4,5,6,7,9]
  dev_subjects: [11]
  

lr_scheduler:
  select: OneCycleLR
  total_steps: 6800
  pct_start: 0.2
  max_lr: 8e-4
model:
  upstream:
    select: EEGPT_PhysioP300
    checkpoint: /home/lingyus/code/PRL/models/upstream/eegpt/checkpoint/eegpt_mcae_58chs_4s_large4E.ckpt

optimizer:
  lr: 8e-4
  select: AdamW
  weight_decay: 0.01            # 权重衰减 (L2正则化)
  

task:
  loss:
    select: CrossEntropyLoss
  select: PhysioP300Task

trainer:
  ddp_backend: gloo
  fp16: true
  total_steps: 6800
  save_interval: 68
  eval_interval: 68
  log_interval: 10
  world_size: 1
  eval_metric: BalancedAccuracy
  metrics:
    acc: {}
    bal_acc: {}
    f1:
      average: 'weighted'
    cohen_kappa: {}
    roc_auc: {}