common:
  seed: 7
  verbose: true
  exp_dir: experiments

dataset:
  batch_size: 64
  dataset: KaggleERNDataset
  num_workers: 0
  path: /mnt/ssd/lingyus
  train_subjects: [2,6,7,11,12,13,14,16,17,18,20,21]
  dev_subjects: [1,3,4,5,8,9,10,15,19,25]
  sessions: [1,2,3,4,5]

lr_scheduler:
  select: OneCycleLR
  total_steps: 6400
  pct_start: 0.2
  max_lr: 4e-4
model:
  upstream:
    select: EEGPT_KaggleERN
    checkpoint: /home/lingyus/code/PRL/models/upstream/eegpt/checkpoint/eegpt_mcae_58chs_4s_large4E.ckpt

optimizer:
  lr: 4e-4
  select: AdamW
  weight_decay: 0.01            # 权重衰减 (L2正则化)
  

task:
  loss:
    select: CrossEntropyLoss
  select: kaggleern_task.KaggleERNTask

trainer:
  fp16: true
  total_steps: 6400
  save_interval: 64
  eval_interval: 64
  log_interval: 4
  eval_metric: balanced_accuracy
  metrics: [ accuracy, balanced_accuracy, f1_weighted, cohen_kappa]
    

distributed:
  backend: nccl
  world_size: 1
  distributed_no_spawn: false