common:
  seed: 8
  verbose: true
  exp_dir: experiments

dataset:
  batch_size: 32
  dataset: SEEDVDataset
  num_workers: 4
  root_path:
    train: '/home/lingyus/data/SEED-V/EEG_raw'
    dev:
    test: 
  io_path:
    train: "/home/lingyus/data/SEED-V/EEG_raw_processed"
    dev:
    test: 
  io_mode: pickle
  other_params:
    chunk_size: 1000
  split: 
    method: seedv
    split_by: session_id
    seed: 0
    # dev_size: 0.5
    # test_size: 0.33
  offline_transform:
    eeg:
      # PickChannels:
      #   channels: ['FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2', 'F7', 'F8', 'T3', 'T4', 'T5', 'T6', 'A1', 'A2', 'FZ', 'CZ', 'PZ', 'T1', 'T2']
      # OrderChannels:
      #   order: ['FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2', 'F7', 'F8', 'T3', 'T4', 'T5', 'T6', 'A1', 'A2', 'FZ', 'CZ', 'PZ', 'T1', 'T2']
      Filter:
        l_freq: 0
        h_freq: 38
      # NotchFilter:
      #   freqs: [50.0]
      Resample:
        desired_sampling_rate: 200.0
  # online_transform:
    # eeg:
    #   ToIndexChannels:
    #     channels: ['FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2', 'F7', 'F8', 'T3', 'T4', 'T5', 'T6', 'A1', 'A2', 'FZ', 'CZ', 'PZ', 'T1', 'T2']
  
  

lr_scheduler:
  select: OneCycleLR
  total_steps: 6500
  pct_start: 0.2
  max_lr: 4e-4
model:
  upstream:
    select: EEGPT_BCICIV2A
    checkpoint: /home/lingyus/code/PRL/models/upstream/eegpt/checkpoint/eegpt_mcae_58chs_4s_large4E.ckpt

optimizer:
  lr: 4e-4
  select: AdamW
  weight_decay: 0.01            # 权重衰减 (L2正则化)
  

task:
  loss:
    select: CrossEntropyLoss
  select: bciciv2a_eegpt_task.BCICIV2ATask

trainer:
  ddp_backend: gloo
  fp16: true
  total_steps: 6500
  update_interval: 1
  save_interval: 65
  eval_interval: 65
  log_interval: 10
  world_size: 1
  eval_metric: balanced_accuracy
  metrics: [ accuracy, balanced_accuracy, f1_weighted, cohen_kappa]


distributed:
  backend: nccl
  world_size: 1
  distributed_no_spawn: false