common:
  seed: 0
  verbose: true
  exp_dir: experiments

dataset:
  batch_size: 64
  dataset: TUEVDataset
  eval:
  - processed_eval
  - processed_test
  num_workers: 2
  path: /home/lingyus/data/tuh_eeg_events/v2.0.1/edf/processed
  train: processed_train
  transforms:
    select: []

lr_scheduler:
  select: WarmupCosineAnnealingLR
  T_max: 31980
  eta_min: 1e-6
  warmup_start_lr: 0
  warmup_steps: 3198

model:
  downstream:
    classes: 4
    select: mlp
  upstream:
    select: labram_base_patch200_200
    trainable: true
    finetune: /home/lingyus/code/PRL/models/upstream/labram/checkpoints/labram-base.pth
    nb_classes: 6
    drop: 0.0
    drop_path: 0.1
    attn_drop_rate: 0.0
    drop_block_rate: null
    use_mean_pooling: true
    init_scale: 0.001
    rel_pos_bias: false
    abs_pos_emb: true
    layer_scale_init_value: 0.1
    qkv_bias: false

optimizer:
  lr: 5e-4
  select: AdamW
  weight_decay: 0.05             # 权重衰减 (L2正则化)
  layer_decay: 0.65                # 层级学习率衰减

task:
  loss:
    select: LabelSmoothingCrossEntropy
    smoothing: 0.1
  select: tuev_task.TUEVTask

trainer:
  resume:  # 添加断点恢复配置
      enabled: false
      checkpoint: /home/lingyus/code/PRL/experiments/2025-01-10/14-27-21/checkpoint/checkpoint_step_8488.pt
  fp16: true
  total_steps: 31980
  update_interval: 8
  save_interval: 1066
  eval_interval: 1066
  log_interval: 20
  eval_metric: balanced_accuracy
  metrics: [balanced_accuracy, accuracy, f1_weighted, cohen_kappa]
    

distributed:
  backend: nccl
  world_size: 1
  distributed_no_spawn: false