common:
  seed: 2025
  verbose: true
  exp_dir: experiments

dataset:
  batch_size: 256
  dataset: mit_bih_dataset.MITBIHDataset
  num_workers: 4
  root_path:
    train: '/home/lingyus/data/mit-bih-arrhythmia-database-1.0.0'
    dev:
    # test: 
  io_path:
    train: "/home/lingyus/data/mit-bih-arrhythmia-database-1.0.0/processed_wavelet"
    dev: 
    test: 
  io_mode: pickle
  split: 
    method: hold_out
    split_by: clip_id
    stratified: false
    shuffle: true
    seed: 7
    test_size: 0.2
    dev_size: 0.125
    # n_splits: 10
  other:
    pre_offset: 100
    post_offset: 200

  before_trial:
    ecg:
      WaveletTransform:
        wavelet: 'db5'
        level: 9
      # Normalize:
      #   method: zscore_per_channel
  offline_transform:
    ecg:
      PickChannels:
        channels: ['MLII']
      # Normalize:
      #   method: zscore_per_channel

 


lr_scheduler:
  select: WarmupCosineScheduler
  total_epochs: 1000
  eta_min: 1e-6
  warmup_start_lr: 0
  warmup_epochs: 5

model:
  select: conformer.Conformer
  n_outputs: 4
  n_chans: 1
  n_times: 300
  att_depth: 3
  att_heads: 4

  # select: ECGCNN

  # select: EcgResNet34
  # num_classes: 4

  # select: EEGNet
  # n_chans: 1
  # chunk_size: 300
  # num_classes: 4
    

optimizer:
  lr:  0.001
  select: Adam
  # weight_decay: 0.05             # 权重衰减 (L2正则化)
  # layer_decay: 0.65                # 层级学习率衰减

task:
  loss:
    select: FocalLoss
    # smoothing: 0.1
  select: mit_bih_task.MITBIHTask

trainer:
  resume:  # 添加断点恢复配置
      enabled: false
      checkpoint: /home/lingyus/code/PRL/experiments/2025-01-10/14-27-21/checkpoint/checkpoint_step_8488.pt
  fp16: true
  # total_steps: 31980
  total_epochs: 1000
  update_interval: 1
  # save_interval: 1066
  # eval_interval: 1066
  log_interval: 20
  eval_metric:
    select: accuracy
    mode: max
  metrics: [accuracy, precision_macro, f1_macro, recall_macro]
    

distributed:
  backend: nccl
  world_size: 1
  distributed_no_spawn: false