common:
  seed: 0
  verbose: true
  exp_dir: experiments

dataset:
  batch_size: 64
  dataset: ninapro_db5_dataset.NinaproDB5Dataset
  num_workers: 4
  root_path:
    train: '/mnt/ssd/lingyus/NinaproDB5E2'
    val:
    # test: 
  io_path:
    train: "/mnt/ssd/lingyus/tyee_ninapro_db5/train"
    val: 
    test: 
  io_mode: hdf5
  split: 
    # pretrain
    # select: LeaveOneOutAndHoldOutET
    # init_params:
    #   split_path: /mnt/ssd/lingyus/tyee_ninapro_db5/split_pretrain
    #   stratify: gesture
    #   shuffle: false
    #   test_size: 0.4
    #   group_by: subject_id

    # finetune
    select: HoldOutPerSubjectET
    init_params:
      split_path: /mnt/ssd/lingyus/tyee_ninapro_db5/split_finetune
      stratify: gesture
      shuffle: false
      val_size: 0.4
      test_size: 0.4
    run_params:
      subject: 3
  offline_label_transform:
    - select: Mapping
      mapping:
        0: 0
        17: 1
        18: 2
        20: 3
        21: 4
        22: 5
        25: 6
        26: 7
        27: 8
        28: 9
      source: gesture
      target: gesture
    - select: OneHotEncode
      num: 10
      source: gesture
      target: gesture

  offline_signal_transform:
    - select: Filter
      l_freq: 5.0
      method: iir
      iir_params:
        order: 3
        ftype: butter
        padlen: 12
      phase: zero
      source: emg
      target: emg
    - select: Reshape
      shape: 800  # 16*50 = 800
      source: emg
      target: emg
    - select: ToImage
      length: 16
      width: 50
      resize_length_factor: 1
      native_resnet_size: 224
      cmap: viridis
      source: emg
      target: emg
    - select: ToNumpyFloat16
      source: emg
      target: emg

  online_signal_transform:
    - select: ImageResize
      size: (224, 224)
      source: emg
      target: emg


 


# lr_scheduler:
#   select: WarmupCosineScheduler
#   total_epochs: 400
#   eta_min: 1e-6
#   warmup_start_lr: 0
#   warmup_epochs: 5

model:
  select: resnet18.resnet18
  num_classes: 10

  # pretrain
  pretrained: true
  pretrained_cfg_overlay:
    file: '/home/lingyus/code/emgbench/checkpoint/resnet18/pytorch_model.bin'

  # finetune
  # checkpoint_path: /home/lingyus/code/PRL/experiments/2025-05-23/11-24-05-ninapro_db5_task.NinaproDB5Task/checkpoint/fold_0/checkpoint_best.pt 
  # checkpoint_path: /home/lingyus/code/PRL/experiments/2025-05-23/11-24-05-ninapro_db5_task.NinaproDB5Task/checkpoint/fold_1/checkpoint_best.pt
  # checkpoint_path: /home/lingyus/code/PRL/experiments/2025-05-23/11-24-05-ninapro_db5_task.NinaproDB5Task/checkpoint/fold_2/checkpoint_best.pt
  checkpoint_path: /home/lingyus/code/PRL/experiments/2025-05-23/11-24-05-ninapro_db5_task.NinaproDB5Task/checkpoint/fold_3/checkpoint_best.pt
  # checkpoint_path: /home/lingyus/code/PRL/experiments/2025-05-23/11-24-05-ninapro_db5_task.NinaproDB5Task/checkpoint/fold_4/checkpoint_best.pt
  # checkpoint_path: /home/lingyus/code/PRL/experiments/2025-05-23/11-24-05-ninapro_db5_task.NinaproDB5Task/checkpoint/fold_5/checkpoint_best.pt
  # checkpoint_path: /home/lingyus/code/PRL/experiments/2025-05-23/11-24-05-ninapro_db5_task.NinaproDB5Task/checkpoint/fold_6/checkpoint_best.pt
  # checkpoint_path: /home/lingyus/code/PRL/experiments/2025-05-23/11-24-05-ninapro_db5_task.NinaproDB5Task/checkpoint/fold_7/checkpoint_best.pt
  # checkpoint_path: /home/lingyus/code/PRL/experiments/2025-05-23/11-24-05-ninapro_db5_task.NinaproDB5Task/checkpoint/fold_8/checkpoint_best.pt
  # checkpoint_path: /home/lingyus/code/PRL/experiments/2025-05-23/11-24-05-ninapro_db5_task.NinaproDB5Task/checkpoint/fold_9/checkpoint_best.pt
optimizer:
  lr:  5e-4
  select: Adam
  # weight_decay: 0.05             # 权重衰减 (L2正则化)
  # layer_decay: 0.65                # 层级学习率衰减

task:
  loss:
    select: CrossEntropyLoss
    # smoothing: 0.1
  select: ninapro_db5_task.NinaproDB5Task

trainer:
  fp16: false
  # pretrain
  # total_epochs: 100
  # finetune
  total_epochs: 750
  update_interval: 1
  # eval_interval: 1
  log_interval: 20
  eval_metric:
    select: accuracy
    mode: max
  # metrics: [accuracy, balanced_accuracy, roc_auc_macro_ovr, roc_auc_macro_ovo]
  metrics: [accuracy, balanced_accuracy]
    

distributed:
  backend: nccl
  world_size: 1
  distributed_no_spawn: false