common:
  seed: 42
  verbose: true
  exp_dir: experiments

dataset:
  batch_size: 64
  dataset: osausd_dataset.OSAUSDDataset
  num_workers: 8
  root_path:
    train: '/mnt/ssd/lingyus/Stroke_Unit_dataset/dataset_OSAS.pickle'
    val:
    test: 
  io_path:
    train: "/mnt/ssd/lingyus/tyee_osausd/test"
    val:
    test: 
  io_mode: hdf5
  io_chunks: 14400
  split: 
    select: KFoldCross
    init_params:
      split_path: /mnt/ssd/lingyus/tyee_osausd/split_test
      n_splits: 30
      group_by: subject_id
      shuffle: false
  offline_signal_transform:
    - select: PickChannels
      channels: ['II']
      source: ecg
      target: ecg
    # - select: Filter
    #   l_freq: 5.0
    #   h_freq: 35.0
    #   method: iir
    #   iir_params:
    #     order: 2
    #     ftype: butter
    #   source: ecg
    #   target: ecg
    - select: SlideWindow
      window_size: 14400  # 180*80
      stride: 4800       # 60*80
      source: ecg
      target: ecg
    - select: SlideWindow
      window_size: 180
      stride: 60
      source: spo2
      target: spo2
    - select: Select
      key: ['ecg', 'spo2']
  
  offline_label_transform:
    - select: Crop
      crop_left: 60
      crop_right: 60
      source: anomaly
      target: anomaly
    - select: SlideWindow
      window_size: 60
      stride: 60
      source: anomaly
      target: anomaly
    - select: Select
      key: ['anomaly']
  online_signal_transform:
    - select: MinMaxNormalize
      source: ecg
      target: ecg
    - select: MinMaxNormalize
      source: spo2
      target: spo2
    - select: Reshape
      shape: (180, 1)
      source: spo2
      target: spo2
  
  online_label_transform:
    - select: Mapping
      mapping:
        true: 1
        false: -1
      source: anomaly
      target: anomaly


lr_scheduler:
  select: OneCycleScheduler
  max_lr: 1e-2
  epochs: 200
  base_momentum: 0.78
  max_momentum: 0.99

model:
  select: aiosa.Net

optimizer:
  lr: 3e-4
  select: Adam
  amsgrad: false
  eps: 1e-7

task:
  loss:
    select: weightedSquaredHingeLoss

  select: osausd_task.OSAUSDTask

trainer:
  fp16: true
  # total_steps: 31980
  total_epochs: 200
  update_interval: 1
  # save_interval: 1066
  # eval_interval: 1
  log_interval: 20
  max_grad_norm: 1.0
  eval_metric:
    select: accuracy
    mode: max
  metrics: [accuracy, fn, fp, tp, tn]
    

distributed:
  backend: nccl
  world_size: 1
  distributed_no_spawn: false