common:
  seed: 222
  verbose: true
  exp_dir: experiments

dataset:
  batch_size: 32
  dataset: seedv_dataset.SEEDVFeatureDataset
  num_workers: 8
  root_path:
    train: '/mnt/ssd/lingyus/SEED-V'
    val:
    # test: 
  io_path:
    train: "/mnt/ssd/lingyus/tyee_seedv_feature/train"
    val: 
    test: 
  io_mode: hdf5
  io_chunks: 1
  split: 
    select: KFoldPerSubjectCross
    init_params:
      split_path: /mnt/ssd/lingyus/tyee_seedv_feature/split
      group_by: trial_id
      n_splits: 3
      shuffle: false
  offline_signal_transform:
    - select: Log
      epsilon: 1
      source: eog
      target: eog
    - select: SlideWindow
      window_size: 1
      stride: 1
      axis: 0
      source: eeg
      target: eeg
    - select: SlideWindow
      window_size: 1
      stride: 1
      axis: 0
      source: eog
      target: eog

  offline_label_transform:
    - select: SlideWindow
      window_size: 1
      stride: 1
      axis: 0
      source: emotion
      target: emotion

  online_signal_transform:
    - select: MinMaxNormalize
      source: eeg
      target: eeg
    - select: MinMaxNormalize
      source: eog
      target: eog
    - select: Concat
      axis: -1
      source: ["eeg", "eog"]
      target: eeg_eog
    - select: Insert
      indices: [316, 317, 318, 319, 326, 327, 328, 329, 334, 335, 336, 337, 338, 339, 344, 345, 346, 347, 348, 349, 354, 355, 356, 357, 358, 359, 369]
      value: 0
      axis: -1
      source: eeg_eog
      target: eeg_eog
    - select: Squeeze
      axis: 0
      source: eeg_eog
      target: eeg_eog
    - select: Select
      key: ["eeg_eog"]
  online_label_transform:
    - select: Squeeze
      axis: 0
      source: emotion
      target: emotion
    - select: ToNumpyInt64
      source: emotion
      target: emotion
  
lr_scheduler:
  select: StepLRScheduler
  gamma: 0.1
  epoch_size: 300
  warmup_steps: 2000 

model:
  select: g2g.EncoderNet
  head_num: 6
  rand_ali_num: 2
  backbone: "ResNet18"
  # --- RelationAwareness 模块使用的参数 ---
  input_size: 5       # EEG 特征维度 (data_em 输入)
  location_size: 3    # 位置坐标维度 (location_em 输入)
  expand_size: 10     # 嵌入层输出和注意力计算的扩展维度

  # --- EncoderNet 模块使用的参数 ---
  eeg_node_num: 62    # 用于 random_1D_node 生成随机排列
  num_class: 5        # 最终分类器 mlp_1 的输出维度
  sup_node_num: 6
    



optimizer:
  lr:  0.008
  select: AdamW
  weight_decay: 5e-4
  betas: (0.9, 0.999)

task:
  loss:
    select: LabelSmoothingCrossEntropy
    smoothing: 0.01
  select: seedv_task.SEEDVFeatureTask

trainer:
  fp16: false
  # total_steps: 31980
  total_epochs: 300
  update_interval: 1
  # save_interval: 1066
  # eval_interval: 1
  log_interval: 20
  eval_metric:
    select: accuracy
    mode: max
  metrics: [accuracy, balanced_accuracy,precision_macro, f1_macro, recall_macro]
    

distributed:
  backend: nccl
  world_size: 1
  distributed_no_spawn: false