common:
  seed: 2025
  verbose: true
  exp_dir: experiments

dataset:
  batch_size: 12
  dataset: sleepedfx_dataset.SleepEDFCassetteDataset
  num_workers: 8
  root_path:
    train: '/mnt/ssd/lingyus/sleep-edf-20'
    val:
    # test: 
  io_path:
    train: "/mnt/ssd/lingyus/tyee_sleepedfx_20/train"
    val: 
    test: 
  io_mode: hdf5
  io_chunks: 20
  before_segment_transform:
    - select: PickChannels
      channels: ['Fpz-Cz']
      source: eeg
      target: eeg
  
  offline_signal_transform:
    - select: SlideWindow
      window_size: 20
      stride: 20
      axis: 0
      source: eeg
      target: eeg
    - select: SlideWindow
      window_size: 20
      stride: 20
      axis: 0
      source: eog
      target: eog
    - select: Select
      key: ['eeg', 'eog']
  
  offline_label_transform:
    - select: Mapping
      mapping:
        0: 0  # Sleep stage W
        1: 1  # Sleep stage N1
        2: 2  # Sleep stage N2
        3: 3  # Sleep stage N3
        4: 3  # Sleep stage N4
        5: 4  # Sleep stage R
      source: stage
      target: stage
    - select: SlideWindow
      window_size: 20
      stride: 20
      axis: 0
      source: stage
      target: stage
  
  online_signal_transform:
    - select: Compose
      transforms:
        - select: Transpose
          axes: [1, 0, 2]
        - select: Reshape
          shape: [1, -1]  # 20*3000 = 60000
        - select: ExpandDims
          axis: -1
      source: eeg
      target: eeg
    - select: Compose
      transforms:
        - select: Transpose
          axes: [1, 0, 2]
        - select: Reshape
          shape: [1, -1]  # 20*3000 = 60000
        - select: ExpandDims
          axis: -1
      source: eog
      target: eog
  split: 
    select: KFoldCross
    init_params:
      split_path: /mnt/ssd/lingyus/tyee_sleepedfx_20/split_17_20
      group_by: subject_id
      n_splits: 20
      shuffle: false
  
# lr_scheduler:
#   select: StepLRScheduler
#   gamma: 0.1
#   epoch_size: 300
#   warmup_epochs: 1

model:
  select: salient_sleep_net.TwoStreamSalientModel
  config:
    sleep_epoch_len: 3000  # 30s * 100Hz
    preprocess:
      sequence_epochs: 20
    train:
      filters: [16, 32, 64, 128, 256]
      kernel_size: 5  # This is an int in Keras for (k,1) kernels
      pooling_sizes: [10, 8, 6, 4]  # For first 4 encoders
      dilation_sizes: [1, 2, 3, 4]
      activation: 'relu'
      u_depths: [4, 4, 4, 4]  # For first 4 U-Encoders
      u_inner_filter: 16  # middle_layer_filter for UEncoderBlockTorch
      mse_filters: [8, 16, 32, 64, 128]  # Example, adjust as per original
      padding: 'same'



optimizer:
  lr:  0.001
  select: Adam

task:
  loss:
    select: CrossEntropyLoss
    weight: [1.0, 1.80, 1.0, 1.20, 1.25]
  select: sleepedfx_task.SleepEDFxTask

trainer:
  fp16: false
  # total_steps: 31980
  total_epochs: 60
  update_interval: 1
  # save_interval: 1066
  # eval_interval: 1066
  log_interval: 20
  eval_metric:
    select: accuracy
    mode: max
  metrics: [accuracy, precision_macro, f1_macro, recall_macro]
    

distributed:
  backend: nccl
  world_size: 1
  distributed_no_spawn: false