dataset:
  batch_size: 32
  dataset: BCICIV2aDataset
  eval:
    - None
    - None
  num_workers: 2
  path: /home/taoz/data/PhysioSignal/BCICIV2a
  train: None
  # pre_transforms:
  #   - Clip:
  #       start: 3
  #       end: 6
  # post_transforms:
  #   - ToTensor
  #   - Transpose: [1, 0]
  #   - Select:
  #       channel: "Cz"
  #       # ref_channels: "BCICIV2aDataset.CHANNELS_MAT"
  # label_transforms:
  #   - ToTensor

lr_scheduler:
  gamma: 0.1
  select: StepLR
  step_size: 10000

model:
  downstream:
    classes: 4
    num_feat_dim: 752
    select: MIMLP
  upstream:
    select: Wavelet
    trainable: false
  
optimizer:
  lr: 0.001
  select: Adam

task:
  select: WaveletBCICIV2aTask

  loss:
    select: CrossEntropyLoss


trainer:
  ddp_backend: gloo
  fp16: false
  total_steps: 15000
  save_interval: 20
  eval_interval: 20
  log_interval: 100
  world_size: 1
  metrics:
    - accuracy_score
    # - roc_auc_score

